####################################
#
#  Dockerfile for Root the Box
#  v0.1.3 - By Moloch, ElJeffe

FROM python:3.8

RUN apt-get update && apt-get install -y \
    build-essential zlib1g-dev rustc \
    python3-pycurl sqlite3 libsqlite3-dev 

ADD ./setup/requirements.txt /
RUN pip install --no-cache-dir -r /requirements.txt --upgrade

RUN mkdir /tmp/rtb
ADD . /tmp/rtb
COPY ./start.sh /

VOLUME ["/opt/rtb"]
ENTRYPOINT ["/start.sh"]
